src/GrandeTravel/Models/TravelPackage.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace GrandeTravel.Models
{
    public class TravelPackage
    {
        public int TravelPackageId { get; set; }

        
        public string PackageName { get; set; }
        
        public string PhotoLocation { get; set; }

        public string Location { get; set; }

        
        public string PackageDescription { get; set; }

        public string ProviderName { get; set; }

        public int PackagePrice { get; set; }

        public bool Discontinued { get; set; }

        public string Longitude { get; set; }

        public string Latitude { get; set; }

        public string MyUserId { get; set; }
        public MyUser MyUser { get; set; }

        //One TravelPackage has many Bookings
        public IEnumerable<Booking> Bookings { get; set; }

        public IEnumerable<Feedback> Feedbacks { get; set; }

        public IEnumerable<Photo> Photos { get; set; }
    }
}

src/GrandeTravel/ViewModels/StatisticsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GrandeTravel.ViewModels
{
    public class StatisticsViewModel
    {
        public string Labels { get; set; }
        public string  Data { get; set; }
        public string AmountBookings { get; set; }
    }
}

src/GrandeTravel/Controllers/BookingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using GrandeTravel.Services;
using GrandeTravel.Models;
using GrandeTravel.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using MimeKit;
using MailKit.Net.Smtp;
using Braintree;
using Microsoft.AspNetCore.Http;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace GrandeTravel.Controllers
{
    public class BookingController : Controller
    {
        private IRepository<Booking> _bookingRepo;
        private UserManager<MyUser> _userManager;
        private IRepository<TravelPackage> _travelPackageManager;
        private IEmailSender _emailService;

        public BookingController(IRepository<Booking> bookingRepo, UserManager<MyUser> userManager, IRepository<TravelPackage> travelPackageManager, IEmailSender emailService)
        {
            _userManager = userManager;
            _bookingRepo = bookingRepo;
            _travelPackageManager = travelPackageManager;
            _emailService = emailService;
        }

        // GET: /<controller>/
        [Authorize]
        public IActionResult Index()
        {
            var userId = _userManager.GetUserId(User);
            IEnumerable<Booking> list = _bookingRepo.Query(b => b.MyUserId == userId && b.BookingDate > DateTime.Today);
            DisplayAllBookingsViewModel vm = new DisplayAllBookingsViewModel
            {
                Bookings = list,
                total = list.Count()
            };
            return View(vm);
        }

        [Authorize]
        public IActionResult IndexofPast()
        {
            var userId = _userManager.GetUserId(User);
            IEnumerable<Booking> list = _bookingRepo.Query(b => b.MyUserId == userId && b.BookingDate < DateTime.Today);
            DisplayPastBookingsViewModel vm = new DisplayPastBookingsViewModel
            {
                Bookings = list,
                total = list.Count()
            };
            return View(vm);
        }

        [HttpGet]
        [Authorize]
        public IActionResult Create(int id)
        {
            TravelPackage tp = _travelPackageManager.GetSingle(t => t.TravelPackageId == id);
            string today = DateTime.Now.ToString();
            CreateBookingViewModel vm = new CreateBookingViewModel
            {
                TravelPackageName = tp.PackageName,
                TotalCost = tp.PackagePrice,
                TravelPackageId = id               
                
            };
            return View(vm);
        }
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateBookingViewModel vm)
        {
            
            if (ModelState.IsValid)
            {
                TravelPackage tp = _travelPackageManager.GetSingle(t => t.TravelPackageId == vm.TravelPackageId);
                var userId = _userManager.GetUserId(User);
                string voucherCode = Guid.NewGuid().ToString().GetHashCode().ToString("x");
                Booking booking = new Booking
                {
                    BookingDate = vm.BookingDate,
                    TravelPackageId = vm.TravelPackageId,
                    MyUserId = userId,
                    People = vm.People,
                    Name = User.Identity.Name,
                    //xtra Security getting price from database
                    TotalCost = (vm.People * tp.PackagePrice),
                    TravelPackageName = vm.TravelPackageName,
                    VoucherCode = voucherCode,
                    LeftFeedback = false
                };
                _bookingRepo.Create(booking);
                //Send Email
                MyUser user = await _userManager.FindByIdAsync(userId);
                _emailService.SendEmail("grandetravelproject@gmail.com", user.Email, "Your Booking Voucher",
                            "Booking Date : " + booking.BookingDate + "\n" +
                            "Package Name : " + booking.TravelPackageName + "\n" +
                            "Number of People: " + booking.People + "\n" +
                            "Total cost : $" + booking.TotalCost + "\n" +
                            "Expiry Date : " + booking.BookingDate.AddMonths(3) + "\n" +
                            "Voucher Code : " + voucherCode);
                                               

                return RedirectToAction("Details", "TravelPackage", new { id = booking.TravelPackageId});
            }
            return View(vm);
        }

        [HttpGet]
        [Authorize]
        public IActionResult PaymentRecieved(int id)
        {
            Booking booking = _bookingRepo.GetSingle(b => b.BookingId == id);
            booking.PaymentReceived = true;
            _bookingRepo.Update(booking);
            return RedirectToAction("Index");
        }



        //[HttpGet]
        //[Authorize]
        //public IActionResult BraintreePayment(int id)
        //{
        //    var gateway = new BraintreeGateway
        //    {
        //        Environment = Braintree.Environment.SANDBOX,
        //        MerchantId = "t4xzfjwmtbd7dwvh",
        //        PublicKey = "s4ynn5bwvf4sc588",
        //        PrivateKey = "5dcc19cb0bcdbb3c3f24421a9f07961f"
        //    };
        //    var clientToken = gateway.ClientToken.generate();
        //    return View();

        //}

        //[HttpPost]
        //public ActionResult CreatePurchase(FormCollection collection)
        //{
        //    string nonceFromTheClient = collection["payment_method_nonce"];
        //    // Use payment method nonce here
        //}
    }
}

src/GrandeTravel/Controllers/PhotoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using GrandeTravel.Services;
using GrandeTravel.Models;
using GrandeTravel.ViewModels;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace GrandeTravel.Controllers
{

    public class PhotoController : Controller
    {
        private UserManager<MyUser> _userManager;
        private IRepository<TravelPackage> _TravelPackageRepo;
     
        private IHostingEnvironment _HostingEnviro;
        
        private IRepository<Photo> _photoRepo;

        public PhotoController(IRepository<TravelPackage> TravelPackagerepo, IHostingEnvironment HostingEnviro, UserManager<MyUser> userManager, IRepository<Photo> photoRepo)
        {
            _photoRepo = photoRepo;
            _TravelPackageRepo = TravelPackagerepo;           
            _HostingEnviro = HostingEnviro;
            _userManager = userManager;         
           
        }
        // GET: /<controller>/
     
        [HttpGet]
        [Authorize(Roles = "TravelProvider")]
        public IActionResult Create(int id)
        {
            CreatePhotoViewModel vm = new CreatePhotoViewModel
            {
                TravelPackageId = id
            };
            return View(vm);
        }

        [HttpPost]
        [Authorize(Roles = "TravelProvider")]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CreatePhotoViewModel vm, IList<IFormFile> PhotoLocation)
        {
            if (ModelState.IsValid)
            {
                if(PhotoLocation != null)
                {
                    int count = _photoRepo.Query(p => p.TravelPackageId == vm.TravelPackageId).Count() + 2; 
                    if((count -2) + PhotoLocation.Count() > 4)
                    {
                        ModelState.AddModelError("PhotoLocation", "Cannot have more than 5 Photos Per Package!");
                        return View(vm);
                    }                  
                    TravelPackage tp = _TravelPackageRepo.GetSingle(t => t.TravelPackageId == vm.TravelPackageId);
                    foreach (var item in PhotoLocation)
                    {
                        string uploadPath = Path.Combine(_HostingEnviro.WebRootPath, "Media\\TravelPackage");
                        string filename = User.Identity.Name + "-" + tp.PackageName +"-" + count + Path.GetExtension(item.FileName);
                        uploadPath = Path.Combine(uploadPath, filename);
                        using (FileStream fs = new FileStream(uploadPath, FileMode.Create))
                        {
                            item.CopyTo(fs);
                        }
                        string SaveFilename = Path.Combine("Media\\TravelPackage", filename);
                        Photo tempphoto = new Photo
                        {
                            PhotoLocation = SaveFilename,
                            TravelPackageId = vm.TravelPackageId
                        };
                        _photoRepo.Create(tempphoto);
                        count++;
                    }
                    return RedirectToAction("Details", "TravelPackage", new { id = vm.TravelPackageId });
                }
                
            }
            return View(vm);
        }


    }
}

src/GrandeTravel/Views/TravelPackage/Create.cshtml
@model CreateTravelPackageViewModel


<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h2>Create Travel Package</h2>

            <form asp-controller="TravelPackage" asp-action="Create" method="post" role="form" enctype="multipart/form-data" asp-anti-forgery="true">
                <div class="form-group">
                    <label asp-for="PackageName"></label>
                    <input asp-for="PackageName" class="form-control">
                    <span class="text-danger" asp-validation-for="PackageName"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PhotoLocation"></label>
                    <input type="hidden" asp-for="PhotoLocation" class="form-control">
                </div>
                <div class="form-group">
                    <label></label>
                    <input type="file" name="PhotoLocation" class="form-control">
                </div>
             
                <div class="form-group">
                    <label asp-for="Location"></label>
                    <input asp-for="Location" class="form-control">
                    <span class="text-danger" asp-validation-for="Location"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PackageDescription"></label>
                    <input asp-for="PackageDescription" class="form-control">
                    <span class="text-danger" asp-validation-for="PackageDescription"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PackagePrice"></label>
                    <input asp-for="PackagePrice" class="form-control">
                    <span class="text-danger" asp-validation-for="PackagePrice"></span>
                </div>
                <button type="submit" class="btn btn-default">Save</button>
            </form>
        </div>
    </div>
</div>

src/GrandeTravel/Views/TravelPackage/Details.cshtml
@model DisplaySingleTravelPackageViewModel

<div id="bgIndex" class="container"> </div>

    



        <div class="container-fluid" id="detailsContainer">
            <div id="detailsContent">
                <div class="row">
                    <div class="col-lg-4 col-lg-offset-1 col-md-6 col-sm-6 text-center" id="pckDesc">
                        <h1 class="text-center" id="detailsHead"><i><strong>@Model.PackageName</strong></i></h1>
                        <h6 class="text-center"><em>posted by</em> @Model.TravelProviderName</h6>
                        <h4 class="text-center"><i class="fa fa-map-marker localIcon" aria-hidden="true"></i> <strong>@Model.Location</strong></h4>
                        
                        <h2 class="text-center"><strong>Package Description</strong></h2>
                        <p>@Model.PackageDescription</p>
                        <span>from </span><span class="text-center" id="price"><strong>$@Model.PackagePrice</strong></span><br />
                        <a id="BookBtn" asp-controller="Booking" asp-action="Create" asp-route-id="@Model.TravelPackageId" class="btn btn-success" role="button">Book Now</a><br />
                        @if (Model.UserName == User.Identity.Name || User.IsInRole("Admin"))
                        {
                            <a asp-controller="TravelPackage" asp-action="Update" asp-route-id="@Model.TravelPackageId" class="btn btn-warning" role="button">Update</a>
                            <a asp-controller="Photo" asp-action="Create" asp-route-id="@Model.TravelPackageId" class="btn btn-warning" role="button">Add Photos</a>
                            <a asp-controller="TravelPackage" asp-action="Delete" asp-route-id="@Model.TravelPackageId" class="btn btn-danger" role="button">Discontinue</a>

                        }

                    </div>

                    <div class="col-lg-5 col-lg-offset-1  col-md-6 col-sm-6">
                        <div class="panel panel-default" id="detailImg">
                            <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                                <!-- Indicators -->
                                <ol class="carousel-indicators">
                                    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                                    @for (var i = 1; i <= Model.GalleryPhotos.Count(); i++)
                                    {
                                        <li data-target="#carousel-example-generic" data-slide-to="@i"></li>
                                    }
                                                                        
                                </ol>

                                <!-- Wrapper for slides -->
                                <div class="carousel-inner" role="listbox">
                                    <div class="item active carouselImg">
                                        <img class="PackageImg" src="~/@Model.PhotoLocation">                                       
                                    </div>
                                    @foreach (var item in Model.GalleryPhotos)
                                    {
                                        <div class="item carouselImg">
                                            <img class="PackageImg" src="~/@item.PhotoLocation" alt="...">
                                        </div>
                                    }
                                    
                                        
                                    
                                </div>

                                <!-- Controls -->
                                <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                                    <span class="sr-only">Previous</span>
                                </a>
                                <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                                    <span class="sr-only">Next</span>
                                </a>
                            </div>                            
                            <div class="panel-body">
                                <div class="text-center" id="shareIcons"></div>
                            </div>
                        </div>




                        <div class="text-center">

                        </div>

                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-4 col-lg-offset-1 col-md-6  col-sm-6">
                        <div class="text-center" id="ReviewList">
                            <h4>Reviews</h4>
                            <ul id="commentList">
                                @foreach (var item in Model.Feedbacks)
                                {
                                    <li>
                                        @for (int i = 1; i <= item.Rating; i++)
                                        {
                                            <span><i class="fa fa-star detailStars"></i></span>
                                        }
                                        <br />
                                        @item.Comment
                                        <ul>
                                            <li class="text-right"><i>Posted by </i>@item.UserName</li>
                                        </ul>
                                        <hr />
                                    </li>
                                }
                            </ul>
                        </div>



                    </div>
                    <div class="col-lg-5 col-lg-offset-1  col-md-6 col-sm-6">
                        <div class="panel panel-default">
                            <div class="panel-body">
                                <div id="map"></div>
                            </div>
                        </div>

                    </div>

                </div>
            </div>

    </div>

    <script>

        function initMap() {
            var location = {lat: @Model.latitude, lng: @Model.longitude};
            var map = new google.maps.Map(document.getElementById('map'), {
                zoom: 10,
                center: location
            });
            var marker = new google.maps.Marker({
                position: location,
                map: map
            });
        }
    </script>
    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDj-R9D3cBqhiuL4KiJIq8vcQ_nCHouQJQ&callback=initMap&region=AU">
    </script>

src/GrandeTravel/Views/TravelPackage/Index.cshtml
@model DisplayAllTravelPackagesViewModel
@using GrandeTravel.AppCode
@{
    ViewBag.Title = "Grande Travel Index Page";

}

<div id="bgIndex" class="container"> </div>

<div class="container">
   

    <form class="form-inline text-center" asp-controller="TravelPackage" asp-action="Index" id="SearchForm">
        <input id="autocomplete" type="text" class="form-control autocomplete-suggestions" name="searchString" placeholder="Search Here..">
        <input type="number" class="form-control" name="minPrice" placeholder="Min Price">
        <input type="number" class="form-control" name="maxPrice" placeholder="Max Price">
        <input type="submit" class="btn btn-default" value="Search" />
    </form>

    
</div>
<div class="container-fluid" id="IndexContent">

    <h2 class="text-center text-uppercase" id="packageHeader">Our Packages</h2>
    <div class="row">
        <div class="col-lg-10 col-lg-offset-1">



            @{
                int count = 1;
            }
            @foreach (var item in Model.TravelPackageList)
            {
                if (count % 4 == 0)
                {
                    <div class="row">
                        <div class="col-xs-12 col-sm-6 col-md-3 col-lg-3">
                            <div class="thumbnail text-center packageDsp">
                                <a asp-controller="TravelPackage" asp-action="Details" asp-route-id="@item.TravelPackageId"><img src="~/@item.PhotoLocation" class="IndexThumb" /></a>
                                <a asp-controller="TravelPackage" asp-action="Details" asp-route-id="@item.TravelPackageId" class="price"><strong><em>$@item.PackagePrice</em></strong></a>
                                <div class="caption">
                                    <h3 class="text-success"><strong>@item.PackageName</strong></h3>
                                    <p><i class="fa fa-map-marker localIcon" aria-hidden="true"></i> <strong>@item.Location</strong></p>
                                    <p>@item.PackageDescription.Chop(100)</p>
                                    <p>$@item.PackagePrice</p>
                                    <p><a asp-controller="TravelPackage" asp-action="Details" asp-route-id="@item.TravelPackageId" class="btn btn-primary" role="button">Details</a> <a asp-controller="Booking" asp-action="Create" asp-route-id="@item.TravelPackageId" class="btn btn-success" role="button">Book</a></p>
                                </div>
                            </div>
                        </div>
                    </div>

                }
                else
                {
                    <div class="col-xs-12 col-sm-6 col-md-3 col-lg-3">
                        <div class="thumbnail text-center packageDsp">
                            <a asp-controller="TravelPackage" asp-action="Details" asp-route-id="@item.TravelPackageId"><img src="~/@item.PhotoLocation" class="IndexThumb" /></a>
                            <a asp-controller="TravelPackage" asp-action="Details" asp-route-id="@item.TravelPackageId" class="price"><strong><em>$@item.PackagePrice</em></strong></a>
                            <div class="caption">
                                <h3 class="text-success"><strong>@item.PackageName</strong></h3>
                                <p><i class="fa fa-map-marker localIcon" aria-hidden="true"></i> <strong>@item.Location</strong></p>
                                <p>@item.PackageDescription.Chop(100)</p>
                                <p>$@item.PackagePrice</p>
                                <p><a asp-controller="TravelPackage" asp-action="Details" asp-route-id="@item.TravelPackageId" class="btn btn-primary" role="button">Details</a> <a asp-controller="Booking" asp-action="Create" asp-route-id="@item.TravelPackageId" class="btn btn-success" role="button">Book</a></p>
                            </div>
                        </div>
                    </div>

                }
                count++;


            }
        </div>

    </div>

</div>
  
  <script>
      var packages = @Html.Raw(Model.searchList);
  </script>

src/GrandeTravel/Views/TravelPackage/Statistics.cshtml
@model StatisticsViewModel
<script src="~/lib/Chart.js/dist/Chart.min.js"></script>
<script>

        var data = {
    labels: [
        @Html.Raw(@Model.Labels)
    ],
    datasets: [
        {
            data: [@Model.Data],
            backgroundColor: [
                "#446384",
                "#36A2EB",
                "#77CE56",
                "#CCFCE6",
                "#1133FF",
                "#9966FF",
                "#CC8811",
                "#1199CC"
            ],
            hoverBackgroundColor: [
                "#446384",
                "#36A2EB",
                "#77CE56",
                "#CCFCE6",
                "#1133FF",
                "#9966FF",
                "#CC8811",
                "#1199CC"
            ]
        }]
};
    var bardata = {
        labels: [
        @Html.Raw(@Model.Labels)
    ],
    datasets: [
        {
            data: [@Model.AmountBookings],
            label: "Booking dataset",
            backgroundColor: [
                 "#446384",
                "#36A2EB",
                "#77CE56",
                "#CCFCE6",
                "#1133FF",
                "#9966FF",
                "#CC8811",
                "#1199CC"
            ],
            borderColor: [
                "#446384",
                "#36A2EB",
                "#77CE56",
                "#CCFCE6",
                "#1133FF",
                "#9966FF",
                "#CC8811",
                "#1199CC"
            ]
        }]
};
               
            
        
    
            window.onload = function () {
                var ctx1 = document.getElementById("Piecanvas").getContext("2d");
                window.myBar = new Chart(ctx1,
                    {
                        type: 'pie',
                        data: data,
                        options:
                            {
                                title:
                                {
                                    display: true,
                                    text: "Total Booking Sales"
                                },
                                responsive: true,
                                maintainAspectRatio: true
                            }
                    });
                var ctx2 = document.getElementById("Barcanvas").getContext("2d");
                window.myBar = new Chart(ctx2,
                    {
                        type: 'horizontalBar',
                        data: bardata,
                        options:
                            {
                                title:
                                {
                                    display: true,
                                    text: "Total Amount of Bookings"
                                },
                                scales: {
                                    xAxes: [{
                                        ticks: {
                                            beginAtZero: true
                                        }
                                    }]
                                ,
                                    responsive: true,
                                    maintainAspectRatio: true
                                }
                            }
                    });
                var ctx1 = document.getElementById("Piecanvas2").getContext("2d");
                window.myBar = new Chart(ctx1,
                    {
                        type: 'pie',
                        data: bardata,
                        options:
                            {
                                title:
                                {
                                    display: true,
                                    text: "Total Amount of Bookings"
                                },
                                responsive: true,
                                maintainAspectRatio: true
                            }
                    });
                var ctx2 = document.getElementById("Barcanvas2").getContext("2d");
                window.myBar = new Chart(ctx2,
                    {
                        type: 'horizontalBar',
                        data: data,
                        options:
                            {
                                title:
                                {
                                    display: true,
                                    text: "Total Booking Sales"
                                },
                                scales: {
                                    xAxes: [{
                                        ticks: {
                                            beginAtZero: true
                                        }
                                    }]
                                ,
                                    responsive: true,
                                    maintainAspectRatio: true
                                }
                            }
                    });
            }



</script>
<div class="container">
    <div class="row">
        <div class="col-lg-4 col-lg-offset-1 col-md-5 col-sm-6">
            <div style="text-align: center">
                <h2>Total Sales In $</h2>
                <canvas id="Piecanvas"></canvas>
                
            </div>
        </div>
        <div class="col-lg-4 col-lg-offset-1 col-md-5 col-sm-6">
            <div class="mobile-hide" style="text-align: center">
                <h2>Total Sales In $</h2>
                <canvas id="Barcanvas2"></canvas>

            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-lg-offset-1 col-md-5 col-sm-6">
            <div style="text-align: center">
                <h2>Total Amount of Bookings</h2>
                <canvas id="Piecanvas2"></canvas>

            </div>
        </div>
        <div class="col-lg-4 col-lg-offset-1 col-md-5 col-sm-6">
            <div class="mobile-hide" style="text-align: center">
                <h2>Total Amount of Bookings</h2>
                <canvas id="Barcanvas"></canvas>

            </div>
        </div>
    </div>
</div>
  