src/GrandeTravel/Models/Booking.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GrandeTravel.Models
{
    public class Booking
    {
        public int BookingId { get; set; }

        public DateTime BookingDate { get; set; }

        public int TravelPackageId { get; set; }

        public TravelPackage TravelPackage { get; set; }

        public string MyUserId { get; set; }
        public MyUser MyUser { get; set; }

        public string Name { get; set; }

        public int People { get; set; }

        public int TotalCost { get; set; }

        public string TravelPackageName { get; set; }

        public string VoucherCode { get; set; }

        public bool LeftFeedback { get; set; }

        public bool PaymentReceived { get; set; }

    }
}

src/GrandeTravel/Controllers/BookingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using GrandeTravel.Services;
using GrandeTravel.Models;
using GrandeTravel.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using MimeKit;
using MailKit.Net.Smtp;
using Braintree;
using Microsoft.AspNetCore.Http;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace GrandeTravel.Controllers
{
    public class BookingController : Controller
    {
        private IRepository<Booking> _bookingRepo;
        private UserManager<MyUser> _userManager;
        private IRepository<TravelPackage> _travelPackageManager;
        private IEmailSender _emailService;

        public BookingController(IRepository<Booking> bookingRepo, UserManager<MyUser> userManager, IRepository<TravelPackage> travelPackageManager, IEmailSender emailService)
        {
            _userManager = userManager;
            _bookingRepo = bookingRepo;
            _travelPackageManager = travelPackageManager;
            _emailService = emailService;
        }

        // GET: /<controller>/
        [Authorize]
        public IActionResult Index()
        {
            var userId = _userManager.GetUserId(User);
            IEnumerable<Booking> list = _bookingRepo.Query(b => b.MyUserId == userId && b.BookingDate > DateTime.Today);
            DisplayAllBookingsViewModel vm = new DisplayAllBookingsViewModel
            {
                Bookings = list,
                total = list.Count()
            };
            return View(vm);
        }

        [Authorize]
        public IActionResult IndexofPast()
        {
            var userId = _userManager.GetUserId(User);
            IEnumerable<Booking> list = _bookingRepo.Query(b => b.MyUserId == userId && b.BookingDate < DateTime.Today);
            DisplayPastBookingsViewModel vm = new DisplayPastBookingsViewModel
            {
                Bookings = list,
                total = list.Count()
            };
            return View(vm);
        }

        [HttpGet]
        [Authorize]
        public IActionResult Create(int id)
        {
            TravelPackage tp = _travelPackageManager.GetSingle(t => t.TravelPackageId == id);
            string today = DateTime.Now.ToString();
            CreateBookingViewModel vm = new CreateBookingViewModel
            {
                TravelPackageName = tp.PackageName,
                TotalCost = tp.PackagePrice,
                TravelPackageId = id               
                
            };
            return View(vm);
        }
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateBookingViewModel vm)
        {
            
            if (ModelState.IsValid)
            {
                TravelPackage tp = _travelPackageManager.GetSingle(t => t.TravelPackageId == vm.TravelPackageId);
                var userId = _userManager.GetUserId(User);
                string voucherCode = Guid.NewGuid().ToString().GetHashCode().ToString("x");
                Booking booking = new Booking
                {
                    BookingDate = vm.BookingDate,
                    TravelPackageId = vm.TravelPackageId,
                    MyUserId = userId,
                    People = vm.People,
                    Name = User.Identity.Name,
                    //xtra Security getting price from database
                    TotalCost = (vm.People * tp.PackagePrice),
                    TravelPackageName = vm.TravelPackageName,
                    VoucherCode = voucherCode,
                    LeftFeedback = false
                };
                _bookingRepo.Create(booking);
                //Send Email
                MyUser user = await _userManager.FindByIdAsync(userId);
                _emailService.SendEmail("grandetravelproject@gmail.com", user.Email, "Your Booking Voucher",
                            "Booking Date : " + booking.BookingDate + "\n" +
                            "Package Name : " + booking.TravelPackageName + "\n" +
                            "Number of People: " + booking.People + "\n" +
                            "Total cost : $" + booking.TotalCost + "\n" +
                            "Expiry Date : " + booking.BookingDate.AddMonths(3) + "\n" +
                            "Voucher Code : " + voucherCode);
                                               

                return RedirectToAction("Details", "TravelPackage", new { id = booking.TravelPackageId});
            }
            return View(vm);
        }

        [HttpGet]
        [Authorize]
        public IActionResult PaymentRecieved(int id)
        {
            Booking booking = _bookingRepo.GetSingle(b => b.BookingId == id);
            booking.PaymentReceived = true;
            _bookingRepo.Update(booking);
            return RedirectToAction("Index");
        }



        //[HttpGet]
        //[Authorize]
        //public IActionResult BraintreePayment(int id)
        //{
        //    var gateway = new BraintreeGateway
        //    {
        //        Environment = Braintree.Environment.SANDBOX,
        //        MerchantId = "t4xzfjwmtbd7dwvh",
        //        PublicKey = "s4ynn5bwvf4sc588",
        //        PrivateKey = "5dcc19cb0bcdbb3c3f24421a9f07961f"
        //    };
        //    var clientToken = gateway.ClientToken.generate();
        //    return View();

        //}

        //[HttpPost]
        //public ActionResult CreatePurchase(FormCollection collection)
        //{
        //    string nonceFromTheClient = collection["payment_method_nonce"];
        //    // Use payment method nonce here
        //}
    }
}

src/GrandeTravel/Controllers/FeedbackController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using GrandeTravel.Services;
using GrandeTravel.Models;
using GrandeTravel.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace GrandeTravel.Controllers
{
    public class FeedbackController : Controller
    {
        private IRepository<Booking> _bookingRepo;
        private UserManager<MyUser> _userManager;
        private IRepository<TravelPackage> _travelPackageManager;
        private IRepository<Feedback> _feedbackManager;


        public FeedbackController(IRepository<Booking> bookingRepo, UserManager<MyUser> userManager, IRepository<TravelPackage> travelPackageManager, IRepository<Feedback> feedbackManager)
        {
            _feedbackManager = feedbackManager;
            _userManager = userManager;
            _bookingRepo = bookingRepo;
            _travelPackageManager = travelPackageManager;
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [Authorize(Roles = "Customer,Admin")]
        public IActionResult Create(int id)
        {
            Booking booking = _bookingRepo.GetSingle(t => t.BookingId == id);
            //add check for security
            if(booking != null && !booking.LeftFeedback)
            {
                if (booking.MyUserId == _userManager.GetUserId(User))
                {
                    CreateFeedbackViewModel vm = new CreateFeedbackViewModel
                    {
                        TravelPackageId = booking.TravelPackageId,
                        BookingId = booking.BookingId
                    };
                    return View(vm);
                }
            }
            
            return RedirectToAction("AccessDenied", "Account");
            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Customer,Admin")]
        public IActionResult Create(CreateFeedbackViewModel vm)
        {
            if (ModelState.IsValid)
            {
                Booking booking = _bookingRepo.GetSingle(t => t.BookingId == vm.BookingId);
                if (booking != null  && !booking.LeftFeedback)
                {
                    var userId = _userManager.GetUserId(User);
                    Feedback newfeedback = new Feedback
                    {
                        UserName = User.Identity.Name,
                        TravelPackageId = vm.TravelPackageId,
                        MyUserId = userId,
                        Rating = vm.Rating,
                        Comment = vm.Comment
                    };
                    _feedbackManager.Create(newfeedback);
                    booking.LeftFeedback = true;
                    _bookingRepo.Update(booking);

                    return RedirectToAction("Details", "TravelPackage", new { id = newfeedback.TravelPackageId });
                }else
                {
                    return RedirectToAction("AccessDenied", "Account");
                }
                
            }
            return View(vm);
        }
    }
}

src/GrandeTravel/Views/Booking/Create.cshtml
@model CreateBookingViewModel

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h2>Book Travel Package</h2>
            <form asp-controller="Booking" asp-action="Create" method="post" role="form" asp-anti-forgery="true">
                <div class="form-group">
                    <label asp-for="BookingDate"></label>
                    <input asp-for="BookingDate" value="@DateTime.Today" class="form-control">
                    <span class="text-danger" asp-validation-for="BookingDate"></span>
                </div>
                <div class="form-group">
                    <label asp-for="People"></label>
                    <input asp-for="People" class="form-control">
                    <span class="text-danger" asp-validation-for="People"></span>
                </div>
                <div>
                    <div class="form-group">
                        <label>Total Price $</label><span class="text-success" id="totalCost"></span>                      
                    </div>
                    <input type="hidden" asp-for="TravelPackageName" />
                </div>                           
                <div>
                    <input type="hidden" asp-for="TravelPackageId" />
                </div>                
                <button type="submit" class="btn btn-default">Book</button>
            </form>
        </div>
    </div>
</div>

<script>
    var price = @Model.TotalCost;
</script>

src/GrandeTravel/Views/Booking/Index.cshtml
@model DisplayAllBookingsViewModel
<script src="https://www.paypalobjects.com/api/checkout.js"></script>
<h2>Number of Bookings @Model.total</h2>

<table class="table table-striped">
    <tr>
        <th>Booking Date</th><th>Package Name</th><th>Number of People</th><th>Total Cost</th><th>Payment Received</th>
    </tr>
    @foreach (var item in Model.Bookings)
    {
        <tr>
            <td>@item.BookingDate.ToString("dd/MM/yyyy")</td>
            <td>@item.TravelPackageName</td>
            <td>@item.People</td>
            <td>$@item.TotalCost</td>
            @if (@item.PaymentReceived == false)
            {
                string count = "paypal-button" + item.BookingId;
                <td>
                    <span id=@count></span>
                    <script>
        paypal.Button.render({

                env: 'sandbox', // Or 'sandbox',

            commit: true, // Show a 'Pay Now' button

            client: {
                sandbox: 'AZ04clTAL66Jn8yXI9amZ8e0YDByVOGwARF8O2KcDmVytFjQMPljq42DJXBeTBQL9wpPAnX0lLnhzYr1'

            },

            payment: function(data, actions) {
                        return actions.payment.create({
                        transactions: [
                                {
                            amount: { total: @item.TotalCost, currency: 'AUD' }
                            }
                    ]
                });
                    },

            onAuthorize: function(data, actions) {
                return actions.payment.execute().then(function(payment) {
                    
                            window.location.href =  "@Url.Action("PaymentRecieved", "Booking", new { id = item.BookingId })";
                           
                            // You can now show a confirmation message to the customer
                        });
                    }

                }, '#paypal-button' + @item.BookingId);
                    </script>

                </td>
               
            }
            else
            {

                <td>PAID</td>
             }
                                      

        </tr>
    }
</table>

src/GrandeTravel/Views/Booking/IndexofPast.cshtml
@model DisplayPastBookingsViewModel

<h2>Number of Bookings @Model.total</h2>

<table class="table table-striped">
    <tr>
        <th>Booking Date</th>
        <th>Package Name</th>
        <th>Number of People</th>
        <th>Total Cost</th>
        <th>Feedback</th>
    </tr>
    @foreach (var item in Model.Bookings)
    {
        <tr>
            <td>@item.BookingDate.ToString("dd/MM/yyyy")</td>
            <td>@item.TravelPackageName</td>
            <td>@item.People</td>
            <td>$@item.TotalCost</td>
            @if (@item.LeftFeedback != true)
            {
                <td><a asp-controller="Feedback" asp-action="Create" asp-route-id="@item.BookingId" class="btn btn-success" role="button">Add a Feedback</a></td>

            }
            else
            {
                <td>Left Feedback</td>

            }

        </tr>
    }
</table>