src/GrandeTravel/Controllers/BookingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using GrandeTravel.Services;
using GrandeTravel.Models;
using GrandeTravel.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using MimeKit;
using MailKit.Net.Smtp;
using Braintree;
using Microsoft.AspNetCore.Http;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace GrandeTravel.Controllers
{
    public class BookingController : Controller
    {
        private IRepository<Booking> _bookingRepo;
        private UserManager<MyUser> _userManager;
        private IRepository<TravelPackage> _travelPackageManager;
        private IEmailSender _emailService;

        public BookingController(IRepository<Booking> bookingRepo, UserManager<MyUser> userManager, IRepository<TravelPackage> travelPackageManager, IEmailSender emailService)
        {
            _userManager = userManager;
            _bookingRepo = bookingRepo;
            _travelPackageManager = travelPackageManager;
            _emailService = emailService;
        }

        // GET: /<controller>/
        [Authorize]
        public IActionResult Index()
        {
            var userId = _userManager.GetUserId(User);
            IEnumerable<Booking> list = _bookingRepo.Query(b => b.MyUserId == userId && b.BookingDate > DateTime.Today);
            DisplayAllBookingsViewModel vm = new DisplayAllBookingsViewModel
            {
                Bookings = list,
                total = list.Count()
            };
            return View(vm);
        }

        [Authorize]
        public IActionResult IndexofPast()
        {
            var userId = _userManager.GetUserId(User);
            IEnumerable<Booking> list = _bookingRepo.Query(b => b.MyUserId == userId && b.BookingDate < DateTime.Today);
            DisplayPastBookingsViewModel vm = new DisplayPastBookingsViewModel
            {
                Bookings = list,
                total = list.Count()
            };
            return View(vm);
        }

        [HttpGet]
        [Authorize]
        public IActionResult Create(int id)
        {
            TravelPackage tp = _travelPackageManager.GetSingle(t => t.TravelPackageId == id);
            string today = DateTime.Now.ToString();
            CreateBookingViewModel vm = new CreateBookingViewModel
            {
                TravelPackageName = tp.PackageName,
                TotalCost = tp.PackagePrice,
                TravelPackageId = id               
                
            };
            return View(vm);
        }
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateBookingViewModel vm)
        {
            
            if (ModelState.IsValid)
            {
                TravelPackage tp = _travelPackageManager.GetSingle(t => t.TravelPackageId == vm.TravelPackageId);
                var userId = _userManager.GetUserId(User);
                string voucherCode = Guid.NewGuid().ToString().GetHashCode().ToString("x");
                Booking booking = new Booking
                {
                    BookingDate = vm.BookingDate,
                    TravelPackageId = vm.TravelPackageId,
                    MyUserId = userId,
                    People = vm.People,
                    Name = User.Identity.Name,
                    //xtra Security getting price from database
                    TotalCost = (vm.People * tp.PackagePrice),
                    TravelPackageName = vm.TravelPackageName,
                    VoucherCode = voucherCode,
                    LeftFeedback = false
                };
                _bookingRepo.Create(booking);
                //Send Email
                MyUser user = await _userManager.FindByIdAsync(userId);
                _emailService.SendEmail("grandetravelproject@gmail.com", user.Email, "Your Booking Voucher",
                            "Booking Date : " + booking.BookingDate + "\n" +
                            "Package Name : " + booking.TravelPackageName + "\n" +
                            "Number of People: " + booking.People + "\n" +
                            "Total cost : $" + booking.TotalCost + "\n" +
                            "Expiry Date : " + booking.BookingDate.AddMonths(3) + "\n" +
                            "Voucher Code : " + voucherCode);
                                               

                return RedirectToAction("Details", "TravelPackage", new { id = booking.TravelPackageId});
            }
            return View(vm);
        }

        [HttpGet]
        [Authorize]
        public IActionResult PaymentRecieved(int id)
        {
            Booking booking = _bookingRepo.GetSingle(b => b.BookingId == id);
            booking.PaymentReceived = true;
            _bookingRepo.Update(booking);
            return RedirectToAction("Index");
        }



        //[HttpGet]
        //[Authorize]
        //public IActionResult BraintreePayment(int id)
        //{
        //    var gateway = new BraintreeGateway
        //    {
        //        Environment = Braintree.Environment.SANDBOX,
        //        MerchantId = "t4xzfjwmtbd7dwvh",
        //        PublicKey = "s4ynn5bwvf4sc588",
        //        PrivateKey = "5dcc19cb0bcdbb3c3f24421a9f07961f"
        //    };
        //    var clientToken = gateway.ClientToken.generate();
        //    return View();

        //}

        //[HttpPost]
        //public ActionResult CreatePurchase(FormCollection collection)
        //{
        //    string nonceFromTheClient = collection["payment_method_nonce"];
        //    // Use payment method nonce here
        //}
    }
}

src/GrandeTravel/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using GrandeTravel.Services;
using GrandeTravel.Models;
using GrandeTravel.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace GrandeTravel.Controllers
{
    public class ProfileController : Controller
    {
        private UserManager<MyUser> _userManager;
        private IRepository<TravelProviderProfile> _travelProfileRepo;
        private IRepository<CustomerProfile> _customerProfileRepo;
        private IRepository<TravelPackage> _travelPackageRepo;

        public ProfileController(UserManager<MyUser> userManager, IRepository<TravelProviderProfile> travelProfileRepo, IRepository<CustomerProfile> customerProfileRepo, IRepository<TravelPackage> travelPackageRepo)
        {
            _travelProfileRepo = travelProfileRepo;
            _userManager = userManager;
            _customerProfileRepo = customerProfileRepo;
            _travelPackageRepo = travelPackageRepo;
        }

        // GET: /<controller>/
        [HttpGet]
        [Authorize(Roles = "TravelProvider")]
        public async Task<IActionResult> UpdateProviderProfile()
        {
            MyUser user = await _userManager.FindByNameAsync(User.Identity.Name);
            TravelProviderProfile temp = _travelProfileRepo.GetSingle(p => p.UserId == user.Id);
            UpdateProviderProfileViewModel vm = new UpdateProviderProfileViewModel();
            if (temp != null)
            {

                vm.CompanyName = temp.CompanyName;
                vm.Phone = temp.Phone;

            }
            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "TravelProvider")]
        public async Task<IActionResult> UpdateProviderProfile(UpdateProviderProfileViewModel vm)
        {
            if (ModelState.IsValid)
            {
                //who logged in
                var loggedUser = await _userManager.FindByNameAsync(User.Identity.Name);
                //check if there is a profile already
                TravelProviderProfile loggedProfile = _travelProfileRepo.GetSingle(p => p.UserId == loggedUser.Id);
                //create or update
                if (loggedProfile != null)
                {
                    
                    //update the loggedProfile
                    loggedProfile.CompanyName = vm.CompanyName;
                    
                    loggedProfile.Phone = vm.Phone;
                    //save the update to the database
                    _travelProfileRepo.Update(loggedProfile);
                   
                    //update existing Packages For Name Changes
                    IEnumerable<TravelPackage> list = _travelPackageRepo.Query(l => l.MyUserId == loggedUser.Id).ToList();
                    foreach (var item in list)
                    {
                        item.ProviderName = vm.CompanyName;
                        _travelPackageRepo.Update(item);
                    }
                }
                else
                {
                    //create new profile
                    loggedProfile = new TravelProviderProfile
                    {
                        UserId = loggedUser.Id,
                        CompanyName = vm.CompanyName,
                        
                        Phone = vm.Phone
                    };
                    //save the new profile to database
                    _travelProfileRepo.Create(loggedProfile);
                   
                }
                return RedirectToAction("Index", "TravelPackage");
            }

            return View(vm);

        }

        [HttpGet]
        [Authorize(Roles = "Customer")]
        public async Task<IActionResult> UpdateCustomerProfile()
        {
            MyUser user = await _userManager.FindByNameAsync(User.Identity.Name);
            CustomerProfile temp = _customerProfileRepo.GetSingle(p => p.UserId == user.Id);
            UpdateCustomerProfileViewModel vm = new UpdateCustomerProfileViewModel();
            if (temp != null)
            {

                vm.FirstName = temp.FirstName;
                vm.LastName = temp.LastName;
                
                vm.Phone = temp.Phone;

            }
            return View(vm);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Customer")]
        public async Task<IActionResult> UpdateCustomerProfile(UpdateCustomerProfileViewModel vm)
        {
            if (ModelState.IsValid)
            {
                //who logged in
                var loggedUser = await _userManager.FindByNameAsync(User.Identity.Name);
                //check if there is a profile already
                CustomerProfile loggedProfile = _customerProfileRepo.GetSingle(p => p.UserId == loggedUser.Id);
                //create or update
                if (loggedProfile != null)
                {
                    //update the loggedProfile
                    loggedProfile.FirstName = vm.FirstName;
                    loggedProfile.LastName = vm.LastName;
                    
                    loggedProfile.Phone = vm.Phone;
                    //save the update to the database
                    _customerProfileRepo.Update(loggedProfile);
                    
                }
                else
                {
                    //create new profile
                    loggedProfile = new CustomerProfile
                    {
                        UserId = loggedUser.Id,
                        FirstName = vm.FirstName,
                        LastName = vm.LastName,
                        Phone = vm.Phone
                    };
                    //save the new profile to database
                    _customerProfileRepo.Create(loggedProfile);                    
                }
                return RedirectToAction("Index", "TravelPackage");
            }

            return View(vm);

        }
    }
}

src/GrandeTravel/Views/Shared/_Layout.cshtml
@using System.Security.Claims
 
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/CSS/StyleSheet.css" rel="stylesheet" />
    <link href='//fonts.googleapis.com/css?family=Titan One' rel='stylesheet'>
    <link href="~/lib/fontawesome/css/font-awesome.css" rel="stylesheet" />
    <link href="~/lib/jssocials/dist/jssocials.css" rel="stylesheet" />
    <link href="~/lib/jssocials/dist/jssocials-theme-classic.css" rel="stylesheet" />
   
</head>
<body>
    <nav class="navbar navbar-default" id="landingNav">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a id="brandLogo" class="navbar-brand" href="/">Grande Travel &nbsp;<i class="fa fa-plane" style="font-size:larger" aria-hidden="true"></i></a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="TravelPackage" asp-action="Index">Search Packages<span class="sr-only">(current)</span></a></li>
                    <li><a href="~/home/about">About Us</a></li>
                    <li><a href="~/home/contact">Contact</a></li>                 
                    
                </ul>
                <ul class="nav navbar-nav navbar-right" >
                    @if (@User.Identity.IsAuthenticated)
                    {
                        <li class="dropdown" >
                            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                @User.Identity.Name
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                @if (User.IsInRole("Admin"))
                                {
                                    <li class="dropdown-header">Admin Options</li>
                                    <li><a asp-area="" asp-controller="Account" asp-action="AddRole">Add Role</a></li>
                                    <li><a asp-area="" asp-controller="Account" asp-action="RegisterTravelProvider">Add A Travel Provider</a></li>
                                    <li><a asp-area="" asp-controller="Account" asp-action="TravelProviderList">View All Travel Providers</a></li>
                                    <li><a asp-area="" asp-controller="Account" asp-action="CustomerList">View All Customers</a></li>
                                }
                                @if (User.IsInRole("TravelProvider"))
                                { 
                                <li class="dropdown-header">Travel Provider Options</li>
                                <li><a asp-area="" asp-controller="TravelPackage" asp-action="Create">Add Travel Package</a></li>
                                <li><a asp-area="" asp-controller="Profile" asp-action="UpdateProviderProfile">Update Profile</a></li>
                                <li><a asp-area="" asp-controller="TravelPackage" asp-action="Statistics">Statistics</a></li>


                                }                             
                                @if (User.IsInRole("Customer"))
                                {
                                    <li class="dropdown-header">Customer Options</li>
                                    <li><a asp-area="" asp-controller="Profile" asp-action="UpdateCustomerProfile">Update Profile</a></li>
                                    <li><a asp-area="" asp-controller="Booking" asp-action="Index">Display My Bookings</a></li>
                                    <li><a asp-area="" asp-controller="Booking" asp-action="IndexOfPast">Display My Previous Bookings</a></li>
                                    <li role="separator" class="divider"></li>                                  
                                }
                                <li><a><form method="post" asp-controller="Account" asp-action="Logout" asp-anti-forgery="true"><input id="logoutBtn" type="submit" value="Logout" /></form></a></li>
                            </ul>
                        </li>

                            
                            
                    }
                    else
                    {
                        <li><a asp-area="" asp-controller="Account" asp-action="Register">Sign Up</a></li>
                        <li><a asp-area="" asp-controller="Account" asp-action="LogIn">Sign In</a></li>

                    }
                    

                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
    <div>
        @RenderBody()
    </div>
   
    <footer class="container-fluid">
        <div class="row">
            <div class="col-md-4 col-sm-4 col-xs-6">             
                <address>
                    <strong>Grande Travel Corporation</strong><br>
                    <span class="mobile-hide">248 Australia Street, Newtown<br>
                    NSW, AUSTRALIA 2042<br>
                    <abbr title="Phone">P:</abbr> (02) 9758-1132</span>
                    <p>&copy;2016-2017, all rights reserved &reg;</p>
                </address>
                
            </div>
            <div class="col-md-4 col-sm-4 mobile-hide" id="JoeContact">
                <p>Designed and Built by Joe Bonifacio</p>
                <p>JoBonno Web Development&trade;</p>
                <p>&copy;2016-2017, all rights reserved &reg;</p>
            </div>
            <div class="col-md-4 col-sm-4 col-xs-6">
                <div id="social">
                    <div class="btn-group" role="group" aria-label="...">                        
                        <a href="http://www.twitter.com"><i class="fa fa-twitter socialHover" aria-hidden="true"></i></a>
                        <a href="http://www.instagram.com"><i class="fa fa-instagram socialHover" aria-hidden="true"></i></a>
                        <a href=""><i class="fa fa-camera-retro socialHover" aria-hidden="true"></i></a>
                        <a href="https://www.facebook.com/GrandTravel55/"><i class="fa fa-facebook-square socialHover" aria-hidden="true"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    
    <script src="~/lib/jquery/dist/jquery.js"></script>
    
    <script src="~/lib/jssocials/dist/jssocials.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/lib/devbridge-autocomplete/dist/jquery.autocomplete.js"></script>
    
    <script src="~/JS/MyScript.js"></script>
    @if(ViewBag.Title == "Grande Travel Landing Page" || ViewBag.Title == "Grande Travel Index Page")
    {
        <script src="~/JS/AutoCompleteScript.js"></script>
    }

</body>
</html>